version: '3'

services:
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=bitnami123
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/bitnami/mariadb

  moodle:
    image: bitnami/moodle:latest
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=bitnami123
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=Admin@12345
      - MOODLE_EMAIL=admin@example.com
      - MOODLE_SITE_NAME=Turfa Learn
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
  moodle_data:
