name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Test Docker Compose Configuration
      run: docker-compose config
    
    - name: Build Docker Images
      run: docker-compose build
    
    - name: Start Services
      run: |
        docker-compose up -d
        sleep 30
    
    - name: Check Service Health
      run: |
        docker-compose ps
        curl -f http://localhost:8080 || exit 1
    
    - name: Stop Services
      run: docker-compose down -v