name: Test Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Test Docker Compose
      run: |
        docker-compose up -d
        
    - name: Wait for Moodle to start
      run: |
        echo "Waiting for Moodle to initialize..."
        timeout 300 bash -c 'until curl -f http://localhost:8080 &>/dev/null; do sleep 10; done' || true
        
    - name: Check Moodle accessibility
      run: |
        curl -f http://localhost:8080 || exit 1
        echo "✅ Moodle is accessible!"
        
    - name: Show container status
      run: |
        docker-compose ps
        docker-compose logs --tail=50
        
    - name: Cleanup
      if: always()
      run: |
        docker-compose down -v
